movie/home/urls.py
from django.contrib import admin
from django.urls import path
from home import views
# from .views import Index

urlpatterns = [

    path('', views.index,name ="index"),
    path('login/',views.login ,name = "login"),
    path('signup/', views.signup,name = "signup"),
    path('logout/', views.logout,name = "logout"),
    path('account/', views.account,name = "account"),
    path('cart/', views.cart,name = "cart"),
    path('product_view/', views.product_view,name = "product_view"),
    path('about/', views.about,name = "about"),


]

movie/movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]
urlpatterns += static(settings.MEDIA_URL ,document_root = settings.MEDIA_ROOT)

movie/home/models.py
from django.contrib.auth.hashers import check_password
from django.db import models

# Create your models here

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Sub_Category(models.Model):
    name = models.CharField(max_length=200)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category,on_delete=models.CASCADE,null=False,default="")
    sub_category = models.ForeignKey(Sub_Category, on_delete=models.CASCADE,null=False,default="")
    image = models.ImageField(null=True,blank=True)
    name = models.CharField(max_length= 200)
    price = models.IntegerField()
    date = models.DateTimeField(auto_now_add=True)
    detail = models.CharField(max_length= 800,null=True,default="")

    def __str__(self):
        return self.name

    @staticmethod
    def product_ids_for_cart(ids):
        return Product.objects.filter(id__in= ids)# ((id__in)) ka matlab (ids) mai jo list aayega wo sare product humko miljaye ga

    @staticmethod
    def price_all_product(all_products):
        sum = 0
        for p in all_products:
            sum += p.price
        return sum
    @staticmethod
    def product_detail(product_v):
        return Product.objects.filter(id = product_v)

class Customer(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField (max_length=15)
    email = models.EmailField()
    password = models.CharField(max_length=1000)

    def __str__(self):
        return self.first_name

    def isExists(self):
        if Customer.objects.filter(email =self.email):
            return True

    def get_customer_by_email(Email):
        try:
            return Customer.objects.get(email = Email)
        except:
            return False

    def password_checking(Password,password):
        if check_password(Password,password):
            return True

movie/home/forms.py
from django import forms
from .models import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    password2 = forms.CharField(label="Confirm Passwort",widget=forms.PasswordInput)
    class Meta:
        model = User
        fields=["username","first_name","last_name","email",]

movie/home/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from .models import *
from django.contrib.auth.hashers import make_password ,check_password


# Create your views here.
def index(request):
    if request.method == "POST":
        product_id = request.POST.get("product")  #(name= product) in index.html addtocart name
        # print(product_id)
        cart_item = request.session.get("cart_item")
        if cart_item:
            quantity = cart_item.get(product_id)
            if quantity:                                # if product is already in cart then increment the quantity
                cart_item[product_id] = quantity
            else:
                cart_item[product_id] = 1
        else:
            cart_item = {}
            cart_item[product_id] = 1
        request.session["cart_item"] = cart_item
        print(request.session["cart_item"])
        return redirect('index')

    elif request.method == "GET":
        category1 = Category.objects.all()
        categoryID = request.GET.get("category")
        if categoryID:
            product1 = Product.objects.filter(sub_category = categoryID)
        else:
            product1 = Product.objects.all()
        context = {

            "category2":category1,
            "product2":product1
        }
        # print(request.session.get("customer_id"))
        # print(request.session.get("customer_email"))
        return render(request,"store/index.html",context)


#logout
def logout(request):
    request.session.clear()
    return redirect('login')


#login
def login(request):
    if request.method == "GET":
        return render(request, "store/login.html")
    elif request.method == "POST":
        Email = request.POST.get("email")
        Password = request.POST.get("password")
        customer_login = Customer.get_customer_by_email(Email)
        error_message= None
        if customer_login:
            temp = Customer.password_checking(Password,customer_login.password)
            if temp:
                request.session["customer_id"] = customer_login.id
                return redirect("index")
            else:
                error_message = "Email or Password is invalid"
        else:
            error_message = "Email or Password is invalid"

        return render(request,"store/login.html",{"error":error_message})


# signup
def signup(request):
    if request.method == "GET":
        return render(request,"store/signup.html")
    else:
        First_name = request.POST.get("firstname")
        Last_name = request.POST.get("lastname")
        Phone = request.POST.get("phone")
        Email = request.POST.get("email")
        Password = request.POST.get("password")
        Confirm_Password = request.POST.get("confirmpassword")
        value =  {
            "f_name" : First_name,
            "l_name" : Last_name,
            "p_no" : Phone,
            "E_mail" : Email
        }
# customer_signup object
        customer_signup = Customer(first_name=First_name,
                                   last_name=Last_name,
                                   phone=Phone,
                                   email=Email,
                                   password=Password)
# validation
        error_message = None

        if not First_name:
            error_message = "First name Required"
        elif not Last_name:
            error_message = "Last name Required"
        elif not Phone:
            error_message = "Phone Required"
        elif not len(Phone)==10:
            error_message = "Phone Number must be 10 char Long"
        elif not Email:
            error_message = "Email Required"
        elif not Password:
            error_message = "Password Required"
        elif not Confirm_Password:
            error_message = "Confirm Password Required"
        elif Password != Confirm_Password:
            error_message = "Not Matching"
        elif customer_signup.isExists():
            error_message = "Email Already Exists"

# saving customer data
        if not error_message:
            customer_signup.password  = make_password(customer_signup.password)
            customer_signup.save()
            return render(request,"store/index.html")
        else:
            data = {
                "error" : error_message,
                "Value" : value
            }
            return render(request,"store/signup.html", data)


#account
def account(request):
    return render(request,"store/account.html")

#cart
def cart(request):
    if request.method=="GET":
        ids = list(request.session.get("cart_item").keys())
        all_products = Product.product_ids_for_cart(ids)
        all_Price = Product.price_all_product(all_products)
        print(all_Price)
        context = {
            "all_ids": all_products,
            "all_prices":all_Price
        }
        return render(request,"store/cart.html",context)
    else:
        render(request,"store/cart.html")

#view
def product_view(request):
    if request.method == "POST":
        product_v = request.POST.get("product_view")
        print(product_v)
        pro_detail= Product.product_detail(product_v)


    return render(request,"store/view.html",{"product_detail_view":pro_detail})


#about
def about(request):
    return render(request,"store/about.html")

movie/templates/store/aaaaaaa.html
<div class="container">
		<div class="card">
			<div class="container-fliud">

				<div class="wrapper row">
					<div class="preview col-md-6">

						<div class="preview-pic tab-content">

						  <div class="tab-pane active" id="pic-1"><img src="http://placekitten.com/400/252"></div>
						</div>
					</div>
					<div class="details col-md-6">
						<h3 class="product-title">{{i.name}}</h3>
						<div class="rating">
							<span class="review-no">41 reviews</span>
						</div>
						<p class="product-description">{{i.detail}}</p>
						<h4 class="price">current price: <span>₹ {{i.price}}</span></h4>
						<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>

					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>







<div class=" container">
    <div class="mx-auto">
<br>
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">

				<br>
				<br>
				<table class="table">
					<thead>
						<tr>
							<th>Sno.</th>
							<th></th>
							<th>Product</th>
							<th>Price</th>
						</tr>
					</thead>
					<tbody>
						{% for i in product_detail_view %}
						<tr>
							<td>{{forloop.counter}}</td>
							<td><img class="rounded-circle" style="height : 300px" src="{{i.image.url}}"></td>
							<td><strong>{{i.name}}</strong></td>
							<td><strong>₹</strong>  {{i.price}}</td>

						</tr>
						{% endfor %}
					</tbody>
					<tfoot>


					</tfoot>
				</table>
	</div>

    </div>
</div>

movie/templates/store/about.html
{% extends "./base.html" %}


{% block title %} Home  {% endblock %}

{% block content %}
<br>
<br>

<div  class=" container">
	<div class="mx-auto">
		  <div data-new-gr-c-s-check-loaded="14.1042.0" data-gr-ext-installed="">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
<div class="about-section paddingTB60 gray-bg">
                <div class="container">
                    <div class="row">
						<div class="col-md-7 col-sm-6">
							<div class="card bg-dark ">
  <img src="/static/image/background.jpg" class="card-img" alt="...">
  <div class="card-img-overlay">
    <h1 class="card-title">About Mosiv</h1>
    <p class="card-text">It can be an interesting experience looking around at websites
									in particular industries to identify trends and see how they differ from those in other
									industries. In this article, we’ll take a look at the websites of major motion pictures
									to see what types of websites are being created. Movies are a big part of the entertainment
									industry, and in recent years their websites have become increasingly critical to their
									overall success.</p>
    <p class="card-text">sed lobortis pulvinar. Integer laoreet mi id eros porta euismod. Suspendisse potenti. Nulla eros mauris, convallis et sem tempus, viverra hendrerit sapien</p>
  </div>
</div>



						<div class="about-icons">
                            <ul>
                                <li><a href="https://www.facebook.com/"><i id="social-fb" class="fa fa-facebook-square fa-3x social"></i></a> </li>

								<li><a href="https://twitter.com/"><i id="social-tw" class="fa fa-twitter-square fa-3x social"></i></a> </li>
                                <li> <a href="https://plus.google.com/"><i id="social-gp" class="fa fa-google-plus-square fa-3x social"></i></a> </li>

                            </ul>

	        </div>
							</div>
						</div>
						<div class="col-md-5 col-sm-6">
							<div class="about-img">
								<img src="https://devitems.com/preview/appmom/img/mobile/2.png" alt="">
							</div>
						</div>
                    </div>
                </div>
            </div>	<script type="text/javascript">
		</script>
</div>

	</div>
</div>
<br>
<br>
<br>
<br>



{% endblock content %}

movie/templates/store/account.html
{% extends "./base.html" %}


{% block title %} Home  {% endblock %}

{% block content %}

<div class="container">
		<div class="card">
			<div class="container-fliud">
				<br>
				<br>
				<br>
				<br>
				{% for i in product_detail_view %}

				<div class="wrapper row">
					<div class="preview col-md-6">

						<div class="preview-pic tab-content">

						  <div class="tab-pane active" id="pic-1"> <img style="height : 400px" src="{{i.image.url}}"></div>
						</div>
					</div>
					<div class="details col-md-6">
						<h3 class="product-title">{{i.name}}</h3>
						<br>
						<div class="rating">
							<span class="review-no">41 reviews</span>
						</div>
						<span class="product-title">{{i.detail}}</span>
						<br>
				<br>
						<h4 class="price">current price: <span>₹ {{i.price}}</span></h4>
						<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>

					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>





{% endblock content %}

movie/templates/store/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}
      {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Mosiv</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'about' %}">About</a>
        </li>
          <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Recommendations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"></a>
        </li>
        {% for i in category2 %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
             data-bs-toggle="dropdown" aria-expanded="false">
            {{i.name}}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for j in i.sub_category_set.all %}
            <li><a class="dropdown-item" href="/?category={{j.id}}">{{j.name}}</a></li>
            {% endfor %}
          </ul>
        </li>
        {% endfor %}
      </ul>
      </div>

    <div>
      <ul class="navbar-nav me-auto">
        <li class="nav-item">

          <a class="nav-link active" aria-current="page" href="{% url 'account' %}">Account</a>

        </li>
      </ul>
    </div>
      <div class="buttons">
<!--            <a type="button" class="btn btn-outline-success" href="#">Checkout</a>-->
            <a type="button" class="btn btn-outline-warning" href="{% url 'cart'  %}">Cart</a>
          </div>

      <div class="buttons">
        {% if request.session.customer_id  %}
            <a type="button" class="btn btn-outline-info" href="{% url 'logout' %}">Logout</a>
        {% else %}
            <a type="button" class="btn btn-outline-info" href="{% url 'login' %}">Sign in</a>
        {% endif %}
          </div>



   </div>

</nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>


  {% block content %}

{% endblock content %}


 <div class=" container">
    <div class="mx-auto">
      <footer class="row row-cols-3 py-5 my-5 border-top">
      <div class="col">
      <a href="/" class="d-flex align-items-center mb-3 link-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32"><use xlink:href="#"></use></svg>
      </a>
      <h5 class="display-4"><strong>Mosiv</strong></h5>
    </div>

    <div class="col">

    </div>

    <div class="col">
      <h1>Section</h1>
      <ul class="nav flex-column">
        <li class="nav-item mb-2"><a href="/" class="nav-link p-0 text-muted">Home</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Features</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Pricing</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">FAQs</a></li>
        <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">About</a></li>
      </ul>
    </div>

  </footer>
    </div>
  </div>



    <!-- Optional JavaScript; choose one of the two! -->
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>

movie/templates/store/cart.html
{% extends "./base.html" %}


{% block title %} Home  {% endblock %}

{% block content %}

<div class=" container">
    <div class="mx-auto">

<br>
	<div class="row">
		<div class="col-lg-12">
			<div class="box-element">
				<p class="display-4">Cart</p>
				<a  class="btn btn-outline-dark" href="{% url 'index'  %}">&#x2190; Continue Shopping</a>
				<br>
				<br>
				<table class="table">
					<thead>
						<tr>
							<th>Sno.</th>
							<th></th>
							<th>Product</th>
							<th>Price</th>
						</tr>
					</thead>
					<tbody>
						{% for i in all_ids %}

						<tr>
							<td>{{forloop.counter}}</td>
							<td><img class="rounded-circle" style="height : 180px" src="{{i.image.url}}"></td>
							<td><strong>{{i.name}}</strong></td>
							<td><strong>₹</strong>  {{i.price}}</td>

						</tr>
						{% endfor %}
					</tbody>
					<tfoot>
					<tr>
						<th colspan="3"> Total</th>
						<th ><strong>₹</strong>  {{all_prices}}</th>
					</tr>
					</tfoot>
				</table>
	</div>
    </div>
</div>


{% endblock content %}

movie/templates/store/index.html
{% extends "./base.html" %}

{% load static %}

{% block title %} Home  {% endblock %}

{% block content %}
<style>
    .carousel-item{
    height:50rem;
    }

    .o-d-block
    {
    height:60rem;
    }
    .d-block
    {
    height:30rem;
    }
</style>
<div class="container-fluid my-4">

<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" >
      <img src="/static/image/aaa.jpg"  sizes="" class="o-d-block w-100"  alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/static/image/ss.jpg" class="o-d-block w-100"  alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="/static/image/hollywood.jpg" class="o-d-block w-100" alt="...">
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>



<div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3   g-4">
        {% for j in product2 %}
        <div class="col" >
          <div class="card shadow-sm" id = "{{j.id}}">
            <img src="{{j.image.url}}" class="d-block w-100" alt="..." height="500px;" >

            <div class="card-body" >
              <p class="card-text"><strong>{{j.name}}</strong></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
<!--Add to Cart-->
                  <form action="/#{{ j.id}}" method="POST">
                    {% csrf_token %}

                    <input hidden type="text" name="product" class="btn btn-outline-warning" value="{{j.id}}">
                  <input type="submit"   class="btn btn-outline-warning"  value="Add to Cart">

                  </form>

                    <form action="/product_view/" method="POST">
                        {% csrf_token %}
                        <input hidden type="text" name="product_view" class="btn btn-outline-warning" value="{{j.id}}">
                        <input class="btn btn-outline-success "  type="submit" value="View">
                    </form>

                </div>
                <h4 style="display:inline-block; float:right"><strong>₹</strong> {{j.price}} </h4>
              </div>
            </div>
          </div>
        </div>
{% endfor %}
      </div>
    </div>
  </div>



{% endblock content %}

movie/templates/store/login.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>Sign in</title>
  </head>
  <body>
  <div class="container">
    <div class="p-4 m-4">
      <div class="col-lg-5 mx-auto">

          <form action="{% url 'login' %}" method="POST"  >

              <div style="max-width:440px; margin:auto;">
                  <div class="mx-auto m-4">
                  <h1>Sign in</h1>
                </div>

              {% csrf_token %}

                {% if error%}
                <div class="alert alert-danger " role="alert">
                    {{error}}
                </div>
                {% endif %}
                <!-- email -->
                <div class="form-group m-4">
                    <label  ><strong>Email</strong></label>
                    <input required type="email" name="email" value="{{values.email}}" class=" form-control" placeholder="example@gmail.com">
                </div>

                <!-- password -->
                <div class="form-group m-4 ">
                    <label ><strong>Password</strong></label>
                    <input type="password" name="password"  class="form-control " placeholder="********">
                </div>


                <div class="form-group m-4">
                    <input class="btn btn-outline-info col-lg-4" type="submit" value="Login">
                    <a type="button" class="btn btn-outline-success" href="{% url 'signup' %}">Sign up</a>
                </div>

              </div>


  </form>


      </div>
    </div>

  </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

movie/templates/store/view.html
{% extends "./base.html" %}


{% block title %} Home  {% endblock %}

{% block content %}

<div class="container">
		<div class="card">
			<div class="container-fliud">
				<br>
				<br>
				<br>
				<br>
				{% for i in product_detail_view %}

				<div class="wrapper row">
					<div class="preview col-md-6">

						<div class="preview-pic tab-content">

						  <div class="tab-pane active" id="pic-1"> <img style="height : 400px" src="{{i.image.url}}"></div>
						</div>
					</div>
					<div class="details col-md-6">
						<h3 class="product-title">{{i.name}}</h3>
						<br>
						<div class="rating">
							<span class="review-no">41 reviews</span>
						</div>
						<span class="product-title">{{i.detail}}</span>
						<br>
				<br>
						<h4 class="price">current price: <span>₹ {{i.price}}</span></h4>
						<p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>

					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>





{% endblock content %}